### ISSUE TITLE
Implement branch coverage on chosen functions

### ISSUE THREAD

**Issue by zsabbagh** [zsabbagh/algorithms#1]
Manual instrumentation of branch coverage for the following functions.
This is done by writing to the file `data/branch-coverage` with `'a'` (append) flag enabled.
See structure in `tests/__init__.py`.
Each time testing is run, the file is truncated.

- [x] `maximum_flow_bfs` - Zakaria
- [x] `delete_fixup` - Zakaria
- [x] `edmonds_karp` - Einar
- [x] `fix_insert` - Glacier
- [x] `sort_diagonally` - Glacier
- [x] `knuth_morris_pratt` - Einar
- [x] Implement summarising parser

**Comment by einaroddurpall** [comment]
One thing. If we encounter if-statements without else sections, I think we need to add the else section to keep track of those branches. For example:
```
if pattern[i] == pattern[j]:
        branches.add(3)
        j += 1
        pi[i] = j
else:
        branches.add(4)
```
Agree?

**Comment by einaroddurpall** [comment]
> One thing. If we encounter if-statements without else sections, I think we need to add the else section to keep track of those branches. For example:
> 
> ```
> if pattern[i] == pattern[j]:
>         branches.add(3)
>         j += 1
>         pi[i] = j
> else:
>         branches.add(4)
> ```
> 
> Agree?

TA said it was necessary to add the else section.
